[workspace]
resolver = "2"

members = [
    "api",
    "cli",
    "compile",
    "server",
    "tsc_compile",
]

# This is required to nest workspaces https://github.com/rust-lang/cargo/issues/5042
exclude = ["third_party/deno"]

[profile.release]
debug = true
