[package]
name = "cli"
version = "0.6.2"
authors = ["ChiselStrike"]
edition = "2021"

[dependencies]
anyhow = "1.0"
compile = { path = "../compile" }
futures = "0.3.17"
notify = "5.0.0-pre.12"
prost = "0.8.0"
regex = "1.5.4"
serde = "1.0.130"
serde_derive = "1.0.130"
structopt = "0.3.23"
swc_common = "0.14.6"
swc_ecma_ast = "0.58.0"
swc_ecma_parser = "0.78.2"
tokio = { version = "1.11.0", features = ["rt-multi-thread", "net"] }
toml = "0.5.8"
tonic = "0.5.2"

[build-dependencies]
anyhow = "1.0"
tonic-build = "0.5.2"
vergen = { version = "6", default-features = false, features = ["git"] }

[dev-dependencies]
futures = "0.3.17"
lit = "1.0.4"
server = { path = "../server" }

[[bin]]
name = "chisel"
path = "src/main.rs"

[[test]]
name = "integration_tests"
harness = false
