[package]
name = "cli"
version = "0.10.0-dev.0"
authors = ["ChiselStrike"]
edition = "2021"

[dependencies]
anyhow = "1.0"
compile = { path = "../compile" }
endpoint_tsc = { path = "../endpoint_tsc" }
futures = "0.3.17"
handlebars = "4.2.2"
notify = "5.0.0-pre.12"
prost = "0.8.0"
regex = "1.5.4"
serde = "1.0.130"
serde_derive = "1.0.130"
serde_json = "1.0.68"
structopt = "0.3.23"
tempfile = "3.2.0"
tokio = { version = "1.11.0", features = ["rt-multi-thread", "net", "fs"] }
toml = "0.5.8"
tonic = "0.5.2"

[build-dependencies]
anyhow = "1.0"
tonic-build = "0.5.2"
vergen = { version = "6", default-features = false, features = ["git"] }

[dev-dependencies]
futures = "0.3.17"
glob = "0.3.0"
itertools = "0.10.3"
lit = { git = "https://github.com/chiselstrike/lit", rev = "607b0b9" }
rayon = "1.5.1"
server = { path = "../server" }
whoami = "1.2.1"

[[bin]]
name = "chisel"
path = "src/main.rs"

[[test]]
name = "integration_tests"
harness = false
