[package]
name = "cli"
version = "0.1.0"
authors = ["ChiselStrike"]
edition = "2021"

[dependencies]
anyhow = "1.0"
graphql-parser = "0.3.0"
structopt = "0.3.23"
tonic = "0.5.2"
prost = "0.8.0"
tokio = { version = "1.11.0", features = ["full"] }

[build-dependencies]
tonic-build = "0.5.2"

[dev-dependencies]
lit = "1.0.3"
ntest = "0.7.3"
server = { path = "../server" }
futures = "0.3.17"

[[bin]]
name = "chisel"
path = "src/main.rs"
