[package]
name = "compile"
version = "0.11.0-dev.0"
authors = ["ChiselStrike"]
edition = "2021"

[dependencies]
anyhow = "1.0"
swc_common = "0.17.4"
swc_ecmascript = { version = "0.143.0", features = ["codegen", "parser", "visit", "transforms", "typescript"] }

[lib]
name = "compile"
