[package]
name = "compile"
version = "0.8.3"
authors = ["ChiselStrike"]
edition = "2021"

[dependencies]
anyhow = "1.0"
swc_common = "0.17.4"
swc_ecma_codegen = "0.90.0"
swc_ecma_parser = "0.88.2"
swc_ecma_transforms_typescript = "0.80.0"
swc_ecma_visit = "0.51.1"

[lib]
name = "compile"
