[package]
name = "server"
version = "0.0.0"
authors = ["ChiselStrike"]
edition = "2018"

[dependencies]
anyhow = "1.0"
convert_case = "0.4.0"
deno_broadcast_channel = "0.13.0"
deno_core = "0.101.0"
deno_runtime = "0.27.0"
deno_web = "0.50.0"
futures = "0.3.17"
hyper = "0.14.13"
log = "0.4.14"
pretty_env_logger = "0.4.0"
prost = "0.8.0"
serde_json = "1.0.68"
sqlx = { version = "0.5.7", features = [ "any", "postgres", "sqlite", "runtime-tokio-native-tls" ] }
structopt = "0.3.23"
thiserror = "1.0"
tokio = { version = "1.11.0", features = ["full"] }
tokio-stream = { version = "0.1.7", features = ["signal"] }
tonic = "0.5.2"
url = "2.2.2"

[build-dependencies]
tonic-build = "0.5.2"

[[bin]]
name = "chiseld"
path = "src/main.rs"
