[package]
name = "server"
version = "0.7.0-dev.0"
authors = ["ChiselStrike"]
edition = "2021"

[features]
default = []
must_not_suspend = []

[dependencies]
anyhow = { version = "1.0.45", features = ["backtrace"] }
api = { path = "../api" }
async-channel = "1.6.1"
async-mutex = "1.4.0"
base64 = "0.13.0"
deno_core = "0.117.0"
deno_runtime = "0.43.0"
derive-new = "0.5.9"
enclose = "1.1"
enum-as-inner = "0.3.3"
env_logger = "0.9.0"
format-sql-query = "0.4.0"
futures = "0.3.17"
http = "0.2.6"
hyper = { version = "0.14.16", features = ["server", "tcp", "http1"] }
itertools = "0.10.1"
log = "0.4.14"
nix = "0.22.2"
once_cell = "1.8.0"
pin-project = "1"
prost = "0.8.0"
rand = "0.8.4"
regex = "1"
reqwest = { version = "=0.11.7", features = ["rustls-tls"], default-features = false } # strict = because of https://github.com/seanmonstar/reqwest/issues/1403
rsa = "0.5.0"
sea-query = { version = "0.17.1", features = [ "thread-safe" ] }
serde = "1.0.133"
serde_derive = "1.0.133"
serde_json = "1.0.68"
socket2 = { version = "0.3.18", features = ["unix", "reuseport"] }
sqlx = { version = "0.5.7", features = [ "any", "postgres", "sqlite", "runtime-tokio-rustls" ] }
structopt = "0.3.23"
tempdir = "0.3.7"
tempfile = "3.2.0"
thiserror = "1.0"
tokio = { version = "1.11.0", features = ["rt", "time"] }
tonic = "0.5.2"
tsc_compile = { path = "../tsc_compile" }
url = "2.2.2"
urldecode = "0.1.1"
uuid = { version = "0.8.2", features = ["v4"] }
yaml-rust = "0.4"

[build-dependencies]
anyhow = "1.0"
tonic-build = "0.5.2"
vergen = { version = "6", default-features = false, features = ["git"] }

[lib]
name = "chisel_server"
path = "src/lib.rs"

[[bin]]
name = "chiseld"
path = "src/main.rs"
