[package]
name = "server"
version = "0.1.0"
authors = ["ChiselStrike"]
edition = "2021"

[dependencies]
anyhow = { version = "1.0.45", features = ["backtrace"] }
async-channel = "1.6.1"
async-mutex = "1.4.0"
async-recursion = "0.3.2"
convert_case = "0.4.0"
deno_broadcast_channel = "0.19.0"
deno_core = "0.107.0"
deno_runtime = "0.33.0"
deno_web = "0.56.0"
enclose = "1.1"
futures = "0.3.17"
hyper = { git = "https://github.com/hyperium/hyper", rev = "1d553e52c6953ea3b039f5c3f89d35cb56e2436a", features = ["server", "tcp", "http1"] }
itertools = "0.10.1"
log = "0.4.14"
nix = "0.22.2"
once_cell = "1.8.0"
pretty_env_logger = "0.4.0"
prost = "0.8.0"
regex = "1"
reqwest = "0.11.6"
sea-query = { version = "0.17.1", features = [ "thread-safe" ] }
serde_json = "1.0.68"
socket2 = { version = "0.3.18", features = ["unix", "reuseport"] }
sqlx = { version = "0.5.7", features = [ "any", "postgres", "sqlite", "runtime-tokio-native-tls" ] }
structopt = "0.3.23"
swc_common = "0.14.6"
swc_ecma_codegen = "0.80.0"
swc_ecma_parser = "0.78.2"
swc_ecma_transforms_typescript = "0.61.2"
swc_ecma_visit = "0.44.0"
thiserror = "1.0"
tokio = { version = "1.11.0", features = ["rt"] }
tonic = "0.5.2"
url = "2.2.2"
urldecode = "0.1.1"
uuid = { version = "0.8.2", features = ["v4"] }
v8 = "0.34.0"
yaml-rust = "0.4"

[build-dependencies]
tonic-build = "0.5.2"

[lib]
name = "chisel_server"
path = "src/lib.rs"

[[bin]]
name = "chiseld"
path = "src/main.rs"
