[package]
name = "utils"
version = "0.11.0-dev.0"
authors = ["ChiselStrike"]
edition = "2021"

[dependencies]
anyhow = "1.0.56"
reqwest = { version = "=0.11.10", features = ["rustls-tls"], default-features = false } # strict = because of https://github.com/seanmonstar/reqwest/issues/1403

[lib]
